language: generic
sudo: required
services:
        - docker
before_install:
        - docker build -t sayak1992docker/docker-react -f Dockerfile.dev .
script:
        - docker run -e CI=true sayak1992docker/docker-react npm run test
deploy:
        provider: elasticbeanstalk
        region: "ap-south-1"
        app: "docker"
        env: "Docker-env"
        bucket_name: "elasticbeanstalk-ap-south-1-154217888957"
        bucket_path: "docker"
        on:
                branch: master
access_key_id: $aws_access_key
secret_access_key: $aws_secret_key
