language: generic
sudo: required
services:
        - docker
before_install:
        - docker build -t sayak1992docker/docker-react -f Dockerfile.dev .
script:
        - docker run -e CI=true sayak1992docker/docker-react npm run test
